### ISSUE TITLE
--skip audit unknow parameter

### ISSUE THREAD

**Issue by fxbenard** [wp-cli/i18n-command#137]
Just installed WP-CLI 2.1.0 this morning and :

`$ wp i18n make-pot . languages/test.pot --skip-audit
Error: Parameter errors:
 unknown --skip-audit parameter`

It used to work perfectly with previous version

**Comment by swissspidy** [comment]
I'm afraid I am not able to reproduce this. That command works just fine.

My guess is that you installed the i18n command manually through `wp package install` at some point in the past. Due to a bug in in version prior to 2.1.0, this did not have any effect at all though.\

Please verify the i18n command isn't installed as a separate package by running `wp package list`.

**Comment by fxbenard** [comment]
@swissspidy You rock
A wp package install git@github.com:wp-cli/i18n-command.git fixed the issue
You can close this issue, thanks for your time and this great piece of code.

**Comment by swissspidy** [comment]
I don't think that should have been needed, but if it works for you 👍
