### ISSUE TITLE
i18n make-pot and minified js files

### ISSUE THREAD

**Issue by idea--list** [wp-cli/i18n-command#140]
Hi there,

Developing my first block plugins for GB i noticed a strange behaviour i just can not figure out:

If i write a plugin out of scratch then with wp i18n make-pot all the translatable strings will get extracted from all the .js files and after finishing the conversion to .json file and using wp_set_script_translations() the strings originated from .js files get translated just as expected.

However if i am using boilerplates like create-guten-block, then i18n make-pot extracts strings from .js files located under /src/blocks (where we just develop them), but it simply does not extract any strings from the file /dist/block.build.js even after running npm run build. Now that is a problem as WP uses this file in GB editor, but in the .pot file there are no references to this .js file and as a consequense no string located in the production .js file gets translated.

I just wonder if it is because that file is minified. 
Can anyone confirm if this is a bug or am i doing something not the right way?

Regards

**Comment by schlessera** [comment]
This will probably due to the way the build system for `create-guten-block`is set up, I assume the strings are encoded/wrapped in such a way that our parser doesn't detect them.

**Comment by swissspidy** [comment]
> However if i am using boilerplates like create-guten-block, then i18n make-pot extracts strings from .js files located under /src/blocks (where we just develop them)

That's actually a good thing, because when translators want to see where strings are used, they can just check out the source.

> Now that is a problem as WP uses this file in GB editor, but in the .pot file there are no references to this .js file and as a consequense no string located in the production .js file gets translated.

What does the POT file have to do with this?

As long as your JSON files are named `textdomain-locale-scripthandle.json` then WP will use them for translations just fine.

**Comment by idea--list** [comment]
Sorry to report the bug.
But maybe it would make more sense to go and try what i described and you
will find the same: if using boilerplates and/or if the js file is
minified, the strings simply won't get translated.

Am Di., 12. Feb. 2019, 10:55 hat Pascal Birchler <notifications@github.com>
geschrieben:

**Comment by schlessera** [comment]
All bug reports are welcome.

Please do me the favor and keep a friendly and constructive attitude, though. @swissspidy is just making sure that your expectations are correct before we spend too much time on going through the code. That is standard procedure for maintaining a complex piece of code like WP-CLI.

If your expectations are indeed the correct ones but you still don't get the result you should, then we will of course further investigate what the issue might be.

Thanks!

**Comment by idea--list** [comment]
I really was not unfriendly.
I reported a phenomenon and just got a strange response instead of looking
into the problem.

That is why i responded it would make more sense trying to write a block
with minified js files and/or with boilerplates.

If i was a great js programmer i would have proposed a patch, but
unfortunately i am not so i just can report a bug.

Cheers!

Am Di., 12. Feb. 2019, 11:13 hat Alain Schlesser <notifications@github.com>
geschrieben:

**Comment by swissspidy** [comment]
It was definitely not my intention to offend you or anything.

It would be really helpful if you could give us more information about your setup, i.e. file names, folder structure, text domain, etc. Because "it won't get translated" is very broad.

https://pascalbirchler.com/internationalization-in-wordpress-5-0/ has a good tutorial of how to get things running.

As I said before, it's probably just an issue of naming your JSON files properly.

**Comment by idea--list** [comment]
Thanks, will write a summary what exactly i was doing.

Am Di., 12. Feb. 2019, 11:35 hat Pascal Birchler <notifications@github.com>
geschrieben:

**Comment by ataylorme** [comment]
Instead of creating a new issue, I am going to add to this existing one and hopefully clarify what I see as the potential issue. If I should make a new issue instead, please let me know and I will migrate this comment to a new issue.

I am struggling with minified JavaScript files being ignored by the `i18n make-pot` command [implementing translations in WP Rig](https://github.com/wprig/wprig/pull/551).

The WP Rig starter theme, and other projects (e.g. the `create-guten-block` framework mentioned here), have both source JavaScript files and compiled, minified JavaScript files.

The JavaScript developers write is run through a build process and turned into the JavaScript files consumed by WordPress. This may mean transpiling JavaScript not yet supported by browsers, running minification, etc.

An example of our specific directory structure is:

```sh
assets/js
├── customizer.min.js
├── editor-filters.min.js
├── lazyload.min.js
├── navigation.min.js
└── src
    ├── customizer.js
    ├── editor-filters.js
    ├── lazyload.js
    └── navigation.js
```

Files in `assets/js/src` are the ones edited by developers and a gulp build process creates the files in `assets/js` that are used by WordPress.

Even when the gulp build process uses the `keep_fnames` [option of `uglify`](https://github.com/mishoo/UglifyJS2#minify-options), which will keep all function names from being transformed, `wp i18n make-pot` ignores JavaScript files with `.min` in the name.

However, these are the files I wish to generate a `.pot` file from as they are the ones being enqueued in WordPress, not the source files.

WP-CLI has [a hard-coded `exclude` array for the `i18n make-pot` command](https://github.com/wp-cli/i18n-command/blob/master/src/MakePotCommand.php#L45) that can not be overwritten with the `--include` or `--exclude` options.

I would like for a way to negate the exclusion of minified JavaScript files when creating the `.pot` file in this case (they should remain excluded by default).

Maybe a new option `force_include` which gets run after `include` and `exclude`?

**Comment by swissspidy** [comment]
@ataylorme That sounds really unrelated to the issue at hand here. Would you mind opening a separate one? Thanks in advance! Also note that this should actually work since at least #87. Please verify that you are using the latest version of the package.
