### ISSUE TITLE
make-json: generated file missing theme textdomain prefix

### ISSUE THREAD

**Issue by mcguffin** [wp-cli/i18n-command#197]
## Bug Report

I'll keep it brief – might hopefully save someones time. ;)

**Translations folder** in a theme – just as expected by `load_theme_textdomain()`:
```
languages/
    theme-slug.pot
    de_DE.po
    de_DE.mo
```

**CLI Command**
```
wp i18n make-json languages/*.po --no-purge
```

**The result**
```
languages/
    theme-slug.pot
    de_DE.po
    de_DE.mo
    languages/de_DE-a0623ef93657e56554c5ddda522ed690.json
```

The translation will not load.  
`wp_set_script_translations()` expects the file to live in `{textdomain}-{locale}-{md5}.json`.  
After renaming it accordingly the translation loads.

**Comment by swissspidy** [comment]
Related: https://github.com/wp-cli/i18n-command/issues/151#issuecomment-479493274

**Comment by swissspidy** [comment]
Just copying my comment from the above ticket, which still seems accurate:

`wp i18n make-json` does indeed not support a `--domain` because it is actually not used. That is indeed problematic.

The script just turns `<source>.po` into `<source>-hash.json`, which does not work as you mentioned.

I think the solution here should be:

1. Check `--domain` argument for text domain
1. If not passed, check PO file for `X-Domain` header.
2. Prefix JSON file with text domain in case it is missing.
