### ISSUE TITLE
JS parser breaks on regex

### ISSUE THREAD

**Issue by swissspidy** [wp-cli/i18n-command#223]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

@davilera shared this snippet here: https://gist.github.com/davilera/d624093216cffa13a69f86cf595d4fe5

The `make-pot` command currently fails on it:

```
Debug: Could not parse file a.js: Unexpected } (line 1142, column 0) (0.351s)
```

**Describe how other contributors can replicate this bug**

Run  thee `make-pot` command against the file above.

**Describe what you would expect as the correct outcome**

No parse error

**Let us know what environment you are running this on**

N/A

**Provide a possible solution**

I was hoping updating the Peast package will

**Provide additional context/Screenshots**

N/A

**Comment by davilera** [comment]
I think I know what's amiss! The original, non-minified script, contained the following snippet:

```js
text.replace( /{{/g, '{\u2060{' ).replace( /}}/g, '}\u2060}' );
```

which, as you can see, has a special UTF character. `\u2060` is a [zero width non-breaking space](https://www.fileformat.info/info/unicode/char/2060/index.htm).

If one runs `npm run start`, scripts aren't minified and the previous snippet becomes, well, almost the same (it only changed the quotation marks):

```js
text.replace(/{{/g, "{\u2060{").replace(/}}/g, "}\u2060}")
```

But if one runs `npm run build`, scripts are minified and the UTF character `\u2060` is replaced by the actual character it represents, resulting in this:

```js
e.replace(/{{/g, "{⁠{")
```

which does contain the weird character. So now the following questions arise:

1. Should this character trigger an issue in the parser?
2. I'm using `wp-scripts`. Is it possible to configure _webpack_ so that UTF characters like `\u2060` aren't transformed and mainatined as `\uxxxx`?

**Comment by davilera** [comment]
Sorry, guys, the UTF character `\u2060` was not causing the issue. Instead, it's the regular expression `/}}/g`.

Given a JavaScript as simple as this one:

```js
function a(v) {
  return v.replace( /}/g, '' );
}
```

running `make-pot` produces the parsing error @swissspidy reported:

```
Debug: Parsing file a.js (0.068s)
Debug: Could not parse file a.js: Unexpected } (line 3, column 0) (0.09s)
```

**Comment by davilera** [comment]
FWIW, defining the regular expression as follows:

```js
function a(v) {
	return v.replace( new RegExp( '}', 'g' ), '' );
}
```

seems to "fix" the issue.

**Comment by swissspidy** [comment]
Is this still an issue?

Peast now seems to be parsing this just fine.
