### ISSUE TITLE
Error if translators comment does not match string placeholders

### ISSUE THREAD

**Issue by kkmuffme** [wp-cli/i18n-command#279]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Filed as bug, bc I think this was working before, some years ago? (I'm on wp-cli 2.5.0)

1) There should be an error, if the placeholders in a string, do not match the placeholders in the translators comment.
e.g.

```
// translators: %s: world
_e( 'hello %1$s', 'demo' );
=> string uses %1$s, but translators comment %s

// translators: %1$s: world
_e( 'hello %1$s and %2$s', 'demo' ); 
=> translators comment is missing %2$s
```

2) There should be an error if multiple %s are used instead of %1$s/%2$s

```
// translators: %s: world, %s: Mars
_e( 'hello %s and %s', 'demo' ); 
```

**Comment by swissspidy** [comment]
Thanks for raising this.

I am not aware of any recent changes to this built-in audit, so it might be more of an enhancement.

As such, it might be better suited for projects like `@wordpress/eslint-plugin` and `wp-coding-standards/wpcs` so that such errors are already caught during development and not later on when creating POT files.

```js
// translators: %1$s: world
_e( 'hello %1$s and %2$s', 'demo' ); 
=> translators comment is missing %2$s
```

The preferred way of writing comments like this in WP core is actually `translators: 1: world. 2: xyz`

> There should be an error if multiple %s are used instead of %1$s/%2$s

This should already be caught by this command, WPCS _and_ `@wordpress/eslint-plugin`.

Have you tried running this command with the debug flag? e.g. `wp i18n make-pot --debug`?

**Comment by swissspidy** [comment]
> 2. is not working.
>    I ran with --debug, but there are no errors or anything noteworthy.
> 
> I get all kinds of " has X different translator comments", but no error for this.

Ah, you're right!

I misread your comment to be about `_e( 'hello %s and %s', 'demo' ); ` ([which is correctly detected](https://github.com/wp-cli/i18n-command/blob/134784db520f29d33d48543f98cd766c9709c572/features/makepot.feature#L823-L849)) and not the incorrect translators comment. Sorry about that.

In that case, this could also be detected by WPCS itself.
