### ISSUE TITLE
Wrong string extracted from JS due to bad argument parsing

### ISSUE THREAD

**Issue by anomiex** [wp-cli/i18n-command#294]
## Bug Report

- [x] Yes, I reviewed the [contribution guidelines](https://make.wordpress.org/cli/handbook/contributing/).
- [x] Yes, more specifically, I reviewed the guidelines on [how to write clear bug reports](https://make.wordpress.org/cli/handbook/bug-reports/).

**Describe the current, buggy behavior**

Argument parsing in some cases will ignore an argument entirely, shifting subsequent args into incorrect interpretation.

**Describe how other contributors can replicate this bug**

Create this file
```js
__( `This is a ${ bug }`, 'domain' );
```
Then run `wp i18n make-pot --ignore-domain` over it. Examine the output pot file. It will contain an entry with msgid "domain".

**Describe what you would expect as the correct outcome**

No message is included in the pot file, as the `__()` call does not pass a literal as the msgid.

**Let us know what environment you are running this on**

```
OS:	Linux 5.15.0-2-amd64 #1 SMP Debian 5.15.5-1 (2021-11-26) x86_64
Shell:	
PHP binary:	/usr/bin/php8.0
PHP version:	8.0.13
php.ini used:	/etc/php/8.0/cli/php.ini
MySQL binary:	/usr/bin/mysql
MySQL version:	mysql  Ver 8.0.27-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
SQL modes:	
WP-CLI root dir:	phar://wp-cli.phar/vendor/wp-cli/wp-cli
WP-CLI vendor dir:	phar://wp-cli.phar/vendor
WP_CLI phar path:	/tmp
WP-CLI packages dir:	
WP-CLI global config:	/root/.wp-cli/config.yml
WP-CLI project config:	
WP-CLI version:	2.5.1-alpha-3d81d19
```

**Provide a possible solution**

The relevant code path is at https://github.com/wp-cli/i18n-command/blob/17606058b2d269c1434a9e2269043dec9bf81300/src/JsFunctionsScanner.php#L108-L136

Every code path through the loop should add exactly one entry to `$args[]`. As it is now, if it's not an Identifier, *Expression, Literal, or TemplateLiteral-with-0-expressions then no addition is made.

**Provide additional context/Screenshots**

None

**Comment by swissspidy** [comment]
> [...] or TemplateLiteral-with-0-expressions then no addition is made.

That's by design.

Expressions in template literals cannot be extracted.

True, `domain` being the msgid is incorrect. However, the expected result here would be for this call to be skipped entirely.

`This is a ${ bug }` can't really be extracted. We do not evaluate code and thus we don't know what `bug` is. A translator cannot translate this.

You might think that we could extract the whole `This is a ${ bug }` string as the msgid. But then translators might incorrectly translate `${ bug }` into their language, breaking your code.

An alternative would be to extract `This is a`, but that's not translatable either because it's an incomplete sentence.

I recommend using `sprintf` with placeholders, like so:

```js
sprintf(
	__( 'This is a $s', 'domain' ),
	bug,
)
```

That's really the only viable approach.

**Comment by anomiex** [comment]
> True, `domain` being the msgid is incorrect. However, the expected result here would be for this call to be skipped entirely.

Yes, that's exactly what I'm saying here.

**Comment by swissspidy** [comment]
Oh, I somehow misread. Glad we're on the same page!

This should be a rather trivial fix to add, but needs some Behat test to verify.
