### ISSUE TITLE
Author URI of the plugin translation string in generated POT file

### ISSUE THREAD

**Issue by henrywright** [wp-cli/i18n-command#387]
When I generate a POT file using `wp i18n make-pot . languages/my-plugin.pot` there seems to be an entry for URI. For example:

```
#. Author URI of the plugin
msgid "https://example.com"
msgstr ""
```

Even though it isn't a "clickable" link, is it a good idea to make this string available for translation?

**Comment by swissspidy** [comment]
That would be true for every translatable string in WordPress. A translator could change every URL to `hack.me`. The plugin author URI is not different in that regard.

On that note, WordPress considers translations to be trusted, and trusts translators to not do this kind of things. That's why there are strict processes in place and translations need to be approved etc.

If you feel like WordPress or translate.wordpress.org should do something to prevent such "maltranslation", this is better suited for https://meta.trac.wordpress.org/, as it's not an issue with WP-CLI.
