### ISSUE TITLE
Display warnings for invalid text domains

### ISSUE THREAD

**Issue by Mte90** [wp-cli/i18n-command#44]
I will explain better, taking this and doing that:
```
wget https://downloads.wordpress.org/plugin/glossary-by-codeat.1.6.2.zip
unzip glossary-by-codeat.1.6.2.zip
cd glossary-by-codeat/
wp i18n make-pot . ./test.pot
```

I am getting a file with this content:
```
# Copyright (C) 2018 Glossary
# This file is distributed under the same license as the Glossary package.
msgid ""
msgstr ""
"Project-Id-Version: Glossary 1.6.2\n"
"Report-Msgid-Bugs-To: https://wordpress.org/support/plugin/glossary-by-codeat\n"
"Last-Translator: FULL NAME <EMAIL@ADDRESS>\n"
"Language-Team: LANGUAGE <LL@li.org>\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"POT-Creation-Date: 2018-07-10T17:17:54+02:00\n"
"PO-Revision-Date: 2018-07-10T17:17:54+02:00\n"
"X-Domain: glossary-by-codeat\n"

#. Plugin Name of the plugin
msgid "Glossary"
msgstr ""

#. Plugin URI of the plugin
msgid "http://codeat.co/glossary"
msgstr ""

#. Description of the plugin
msgid "Easily add and manage a glossary with auto-link, tooltips and more. Improve your internal link building for a better SEO."
msgstr ""

#. Author of the plugin
msgid "Codeat"
msgstr ""

#. Author URI of the plugin
msgid "http://codeat.co"
msgstr ""
```
But seems that is not scanning also if the output is:
```
Plugin file detected.
Success: POT file successfully generated!
```

I was thinking that the issue was generated by #41 but I updated right now the package and tried with the package from the wp.org just to work on the best case.
I say not scanning because is very fast and there isn't a verbose parameter to see what file is scanning to see if is working well.

**Comment by Mte90** [comment]
Thanks for the info.
For the constants is a way to organize better the code and avoid a lot of plain stuff but I can remove it without problems and replace with the slug.

For exclude stuff yes I already know just iIwas wondering why wasn't extracting nothing.
Maybe add a check to help for this cases because I am not the only one doing that that where there aren't strings there is an error?

**Comment by swissspidy** [comment]
> Maybe add a check to help for this cases because I am not the only one doing that that where there aren't strings there is an error?

Interesting thought!

We already print warnings about wrong translator comments (see #33), so this could build upon that.

We just have to decide how to best implement this. I don't have a huge problem with just failing silently right now, as constants shouldn't be used. But I see how a small warning can be helpful.

Right now, the [library](https://github.com/oscarotero/Gettext/blob/37882dc3b58c2357fc6ddc204c1f22f7bb2b6601/src/Utils/PhpFunctionsScanner.php) we use for extracting strings from PHP ignores all constants, and the text domain is `null` in this case.

(If you'd use `__( 'Translate me' )`, the array key won't be set at all. When using a constant, it's set to `null`)

For us, this could be an indicator that a constant was used and that we should print a warning for that string.

Otherwise we'd need to fork the existing class and extend [the relevant parts](https://github.com/oscarotero/Gettext/blob/37882dc3b58c2357fc6ddc204c1f22f7bb2b6601/src/Utils/PhpFunctionsScanner.php#L102-L114) with our own logic.

Interestingly, the library has an option to say "if you see constant X, replace it with string Y". So `__( 'Translate me.' , GT_TEXTDOMAIN );` will be handled as if it were `__( 'Translate me.' , 'glossary-by-codeat' );`.

However, I don't think we should expose that feature. `--ignore-domain` is good enough. Also, we don't have this in the JS extractor.

**Comment by Mte90** [comment]
Agree maybe add only a check that see if there are constants or the pot file is empty can be the most easiest solution.

**Comment by GaryJones** [comment]
- https://github.com/stephenharris/grunt-checktextdomain
- https://github.com/felixzapata/gulp-checktextdomain

(Sadly, neither have their logic extracted into a basic node package)

These packages check for invalid _and missing_ text domains, so there is prior art here in terms of useful behaviour.

**Comment by swissspidy** [comment]
WPCS now has a utility to fix text domains: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/releases/tag/1.2.0

**Comment by javorszky** [comment]
The utility sniff in WPCS actively changes files from what I can read. 

> New WordPress.Utils.I18nTextDomainFixer sniff which can compehensively replace/add text-domains in a plugin or theme.

I would also love some functionality that gives me a list of instances where a domain is either missing, or is different to the one configured in the plugin header. I would want to manually review / change / ignore those, in case I'm using a library, or have another, genuine reason for using a different domain.

For now the grunt-checktextdomain remains, but would love to replace that with something like `wp i18n checktextdomain`.

If you're open for that to be included, I can extract the js code and implement that subcommand.

**Comment by swissspidy** [comment]
> I would also love some functionality that gives me a list of instances where a domain is either missing, or is different to the one configured in the plugin header. I would want to manually review / change / ignore those, in case I'm using a library, or have another, genuine reason for using a different domain.

That's what WPCS does. It gives you a list  _and_ allows you to fix the issues automatically if you want to.

Feel free to look into how we could do these checks in this command instead. It would probably need to be written in PHP though, not JavaScript.

**Comment by javorszky** [comment]
> It would probably need to be written in PHP though, not JavaScript.

I can tackle that part. :)

I'll check out the WPCS bit first. Thanks!

**Comment by swissspidy** [comment]
Closing for now as I think this is better handled by using tools like PHPCS and ESLint.
