### ISSUE TITLE
Allow passing custom headers and comments for POT file

### ISSUE THREAD

**Issue by greatislander** [wp-cli/i18n-command#47]
Currently, `wp i18n make-pot` generates a `.pot` file and adds a link to the WordPress plugin or theme repo page as the `Report-Msgid-Bugs-To` header.

See:

+ https://github.com/wp-cli/i18n-command/blob/master/src/MakePotCommand.php#L375
+ https://github.com/wp-cli/i18n-command/blob/master/src/MakePotCommand.php#L379

For plugins and themes which are not distributed via WordPress repos, adding an optional parameter such as `--bugs_address` could be used to supply an alternate link (e.g. to a GitHub issues page).

**Comment by swissspidy** [comment]
Tools like [grunt-wp-i18n](https://github.com/cedaro/grunt-wp-i18n/blob/develop/docs/makepot.md) also allow specifying a custom copyright comment notice. Would that be needed too in your case?

**Comment by greatislander** [comment]
@swissspidy That would be useful as well, yes.

**Comment by swissspidy** [comment]
Related: https://github.com/wp-cli/wp-cli/issues/4616, https://github.com/wp-cli/entity-command/pull/133

We could add a `--headers` argument that allows passing an associative array in JSON format to add custom headers.

Example:

```
wp i18n make-pot --headers='{"Report-Msgid-Bugs-To":"https://github.com/wp-cli/i18n-command/issues"}'
```

This could also be useful to add other headers if one really wants to (see #48 and #49).

For the copyright notice I'd add a new `--copyright` argument (since it's a comment and not a header) or perhaps a new `--comments` argument that takes a comma separated list of comments to add (overriding the existing copyright notice if used). This would make things much more flexible.

----

I just noticed that the original makepot.php script has a [description field](https://github.com/WordPress/wordpress-develop/blob/335b69cedc8a828af1e2c4fa841fcafac6700fbb/tools/i18n/makepot.php#L85-L144) for projects, e.g. `Translation of the WordPress theme {name} {version} by {author}`. However, that appears to be unused.

We might want to add this as a default comment to the POT file though as it can be useful when opening a POT file without context.

**Comment by greatislander** [comment]
I like the JSON `--headers` idea. Much more flexible than adding a bunch of parameters. I'd be happy to work on a PR for that. And I'd lean towards the `--comments` parameter (again, over specificity that could be limiting).
